### ISSUE TITLE
GLib-GIO-WARNING

### ISSUE THREAD

**Issue by pongells** [oslllo/svg-fixer#60]
Hello, 

when I run the library via node (I have not tested via CLI) I get this warning:
```
(process:16016): GLib-GIO-WARNING **: 18:37:43.785: Unexpectedly, UWP app `microsoft.windowscommunicationsapps_16005.11629.20316.0_x64__8wekyb3d8bbwe' (AUMId `microsoft.win
dowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail') supports 1 extensions but has no verbs
```

It seems to be working anyway, but the warning itself is annoying. Any way this can be fixed or silenced?

Thanks

**Comment by Ghustavh97** [comment]
Hi, thanks for the issue.

1. What are the reproduction steps / code snippet of hoe the package is being called.
2. What is your environment e.g OS, node version etc....

**Comment by pongells** [comment]
Hello,

the warning appears when I require the library:

```
const svgFixer = require('oslllo-svg-fixer');
```

I am on Windows, and using ts-node to run my CLI script (written in typescript), the tsconfig.json is:

```
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "strict": true,
    "lib": [
      "es2019"
    ],
    "types": [
      "node"
    ]
  },
  "include": [
    "src"
  ],
  "exclude": [
    "**/*.spec.ts"
  ]
}

```

node version is 14.16.0 :)

**Comment by Ghustavh97** [comment]
I think this might be caused by they way microsoft outlook was installed on you system, check this out https://stackoverflow.com/questions/67607643/what-does-this-warning-mean-it-happens-every-time-i-restart-the-node-process

I also failed to reproduce it on my side

![Capturewwwww](https://user-images.githubusercontent.com/20132952/144512509-ec218fe7-b477-41e4-ad94-bdbb9d6cbff3.PNG)

![Captureww](https://user-images.githubusercontent.com/20132952/144512398-2a410911-6496-4467-9d83-5304494b0b45.PNG)

**Comment by pongells** [comment]
weird.. well it's a minor inconvenience, I'll try to dig a bit more into it when I get some time. thanks for the feedback :)

**Comment by Ghustavh97** [comment]
no problem, let me know if you find a fix for it and feel free to reopen the issue if the problem is really coming from this package.
